=== fialo4k-a/HTML-CSS-JS/Лабораторная работа№11/xml/index3.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema
xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="contact">
<xs:complexType>
<xs:sequence>
<xs:element name="name"
type="xs:string"/>
<xs:element name="surname"
type="xs:string"/>
<xs:element name="country"
type="xs:string"/>
<xs:element name="city"
type="xs:string"/>
<xs:element name="addres"
type="xs:string"/>
<xs:element name="post"
type="xs:string"/>
<xs:element name="age"
type="xs:string"/>
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:schema>

=== fialo4k-a/HTML-CSS-JS/Лабораторная работа№11/xml/index3.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="../css/index.css"?>

<contact
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="index3.xsd">
    <name>Petr</name>
    <surname>Ivanov</surname>
    <country>Russia</country>
    <city>Moscow</city>
    <address>Krasnopresnenskaya emb., 12-17</address>
    <post>frontend-developer</post>
    <age>35</age>
</contact>
